### ISSUE TITLE
lsp-bash server crashing

### ISSUE THREAD

**Issue by NoahGorny** [sublimelsp/LSP-bash#23]
So after updating to the latest sublime version, `lsp-bash` seems to crash all of the time. I have gathered a diagnostic report:

# Troubleshooting: LSP-bash
## Version
 - LSP: 1.9.0
 - Sublime Text: 4112
## Server Test Run
 - exit code: 1
 - output
```
/home/noah/.cache/sublime-text-3/Package Storage/LSP-bash/10.19.0/language-server/node_modules/web-tree-sitter/tree-sitter.js:1
var Module=void 0!==Module?Module:{};!function(e,t){"function"==typeof define&&define.amd?define([],t):"object"==typeof exports?module.exports=t():window.TreeSitter=t()}(0,function(){var e,t={};for(e in Module)Module.hasOwnProperty(e)&&(t[e]=Module[e]);var r,n,s=[],o="./this.program",_=function(e,t){throw t},a=!1,u=!1;a="object"==typeof window,u="function"==typeof importScripts,r="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,n=!a&&!r&&!u;var i,l,d,c,m,f="";r?(f=u?require("path").dirname(f)+"/":__dirname+"/",i=function(e,t){return c||(c=require("fs")),m||(m=require("path")),e=m.normalize(e),c.readFileSync(e,t?null:"utf8")},d=function(e){var t=i(e,!0);return t.buffer||(t=new Uint8Array(t)),N(t.buffer),t},process.argv.length>1&&(o=process.argv[1].replace(/\\/g,"/")),s=process.argv.slice(2),"undefined"!=typeof module&&(module.export

TypeError: WebAssembly.Global is not a constructor
    at /home/noah/.cache/sublime-text-3/Package Storage/LSP-bash/10.19.0/language-server/node_modules/web-tree-sitter/tree-sitter.js:1:12512
    at /home/noah/.cache/sublime-text-3/Package Storage/LSP-bash/10.19.0/language-server/node_modules/web-tree-sitter/tree-sitter.js:1:144
    at Object.<anonymous> (/home/noah/.cache/sublime-text-3/Package Storage/LSP-bash/10.19.0/language-server/node_modules/web-tree-sitter/tree-sitter.js:1:170)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
```
## Server Configuration
 - command
```json
[
  "${node_bin}", 
  "${server_path}", 
  "start"
]
```
 - shell command
```sh
/usr/bin/node "/home/noah/.cache/sublime-text-3/Package Storage/LSP-bash/10.19.0/language-server/node_modules/bash-language-server/bin/main.js" start
```
 - selector
```
(source.shell.bash)
```
 - priority_selector
```
(source.bash)
```
 - init_options
```json
{}
```
 - settings
```json
{}
```
 - env
```json
{
  "EXPLAINSHELL_ENDPOINT": "", 
  "GLOB_PATTERN": "", 
  "HIGHLIGHT_PARSING_ERRORS": "0", 
  "PATH": "/usr/bin:/usr/bin:"
}
```

## Active view
 - File name
```
/home/noah/open-source/pip/src/pip/_internal/commands/configuration.py
```
 - Settings
```json
{
  "auto_complete_selector": "meta.tag, source - comment - string.quoted.double.block - string.quoted.single.block - string.unquoted.heredoc", 
  "lsp_active": null, 
  "syntax": "Packages/Python/Python.sublime-syntax"
}
```
 - base scope
```
source.python
```

## Project / Workspace
 - folders
```json
[
  "/home/noah/open-source/pip"
]
```
 - is project: True
 - project data:
```json
{
  "folders": [
    {
      "path": "."
    }
  ]
}
```

## LSP configuration

```json
{
  "clients": {
    "bashls": {
      "enabled": true
    }, 
    "clangd": {
      "enabled": true
    }, 
    "pyls": {
      "enabled": true
    }, 
    "rust-analyzer": {
      "enabled": true
    }
  }, 
  "disabled_capabilities": [
    "completion"
  ]
}
```
## System PATH
 - /home/noah/open-source/pip/venv/bin
 - /home/noah/.local/kitty.app/bin
 - /home/noah/.cargo/bin
 - /home/noah/.local/bin
 - /usr/local/sbin
 - /usr/local/bin
 - /usr/sbin
 - /usr/bin
 - /sbin
 - /bin
 - /usr/games
 - /usr/local/games
 - /snap/bin
 - /home/noah/open-source/fzf/bin
 - /home/noah/.local/bin
 - /home/noah/.config/composer/vendor/bin

**Comment by jfcherng** [comment]
This server seems to require node v12. (https://github.com/bash-lsp/bash-language-server/blob/b442cdaa53de3b232d00cc465b18a7eed3430fac/package.json#L20) Though the current LTS node is v14. Node v10 is quite outdated anyway.

**Comment by jfcherng** [comment]
I can confirm node v10 doesn't work in my clean Windows 7 VM but v12 works.
