### ISSUE TITLE
Fresh install crash loop

### ISSUE THREAD

**Issue by bli00** [sublimelsp/LSP-bash#54]
Running into the following initialization error on fresh install (prompt says crash loop):

```
LSP-bash: internal/modules/cjs/loader.js:883
LSP-bash:   throw err;
LSP-bash:   ^
LSP-bash: 
LSP-bash: Error: Cannot find module 'node:child_process'
LSP-bash: Require stack:
LSP-bash: - /Users/<my_username>/Library/Caches/Sublime Text/Package Storage/LSP-bash/14.16.0/language-server/node_modules/bash-language-server/out/server.js
LSP-bash: - /Users/<my_username>/Library/Caches/Sublime Text/Package Storage/LSP-bash/14.16.0/language-server/node_modules/bash-language-server/out/cli.js
LSP-bash:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
LSP-bash:     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
LSP-bash:     at Module.require (internal/modules/cjs/loader.js:952:19)
LSP-bash:     at require (internal/modules/cjs/helpers.js:88:18)
LSP-bash:     at Object.<anonymous> (/Users/bli/Library/Caches/Sublime Text/Package Storage/LSP-bash/14.16.0/language-server/node_modules/bash-language-server/out/server.js:12:30)
LSP-bash:     at Module._compile (internal/modules/cjs/loader.js:1063:30)
LSP-bash:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
LSP-bash:     at Module.load (internal/modules/cjs/loader.js:928:32)
LSP-bash:     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
LSP-bash:     at Module.require (internal/modules/cjs/loader.js:952:19) {
LSP-bash:   code: 'MODULE_NOT_FOUND',
LSP-bash:   requireStack: [
LSP-bash:     '/Users/<my_username>/Library/Caches/Sublime Text/Package Storage/LSP-bash/14.16.0/language-server/node_modules/bash-language-server/out/server.js',
LSP-bash:     '/Users/<my_username>/Library/Caches/Sublime Text/Package Storage/LSP-bash/14.16.0/language-server/node_modules/bash-language-server/out/cli.js'
LSP-bash:   ]
LSP-bash: }
```

**Comment by jfcherng** [comment]
> LSP-bash: Error: Cannot find module 'node:child_process'

I would guess it requires Node.js v16 now.

**Comment by rchl** [comment]
BTW. You can access that setting file from the Command Palette using `Preferences: LSP Utils Settings`.

**Comment by rchl** [comment]
I see that you've bumped minimum required nice version so this should now give error message.
